// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IEncounterSystem {
  function throwBall() external;

  function flee() external;

  function monsterFlee() external;

  function attack() external;

  function monsterAttack() external;

  function heal() external;

  function monsterHeal() external;

  function monsterAction() external;
}
